package de.tum.cit.aet.artemis.featuremodel.validation.domain;

public enum ValidationCode {
    DUPLICATE_FEATURE_ID,
    UNKNOWN_SELECTED_FEATURE,
    MISSING_RELATION_PARENT,
    MISSING_RELATION_CHILD,
    MULTIPLE_ROOT_FEATURES,
    NO_ROOT_FEATURE,
    MANDATORY_FEATURE_MISSING,
    ALTERNATIVE_GROUP_SELECTION_MISSING,
    REQUIRES_CONSTRAINT_VIOLATED,
    EXCLUDES_CONSTRAINT_VIOLATED,
    UNSUPPORTED_EXPRESSION_CONSTRAINT
}
