package de.tum.cit.aet.artemis.featuremodel.extraction.service;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.TreeSet;

import de.tum.cit.aet.artemis.featuremodel.catalog.domain.ArtifactMapping;
import de.tum.cit.aet.artemis.featuremodel.catalog.domain.FeatureModel;
import de.tum.cit.aet.artemis.featuremodel.catalog.domain.FeatureNode;
import de.tum.cit.aet.artemis.featuremodel.export.domain.ArtemisConfigKeyCatalog;
import de.tum.cit.aet.artemis.featuremodel.extraction.domain.ExtractedConfigurationDefault;
import de.tum.cit.aet.artemis.featuremodel.extraction.domain.ExtractedConfigurationDefaults;
import de.tum.cit.aet.artemis.featuremodel.extraction.domain.ModelDiffReport;
import de.tum.cit.aet.artemis.featuremodel.extraction.domain.ReportItem;

/**
 * Regenerates the Artemis config-key catalog from the generated model's overlay mappings and the scanned YAML
 * defaults. The catalog keeps its curated meaning — the keys a generated overlay is allowed to contain with their
 * accepted value types — but its content and commit pin become scan outputs instead of a manually re-verified
 * artifact. Value types are derived from the scanned defaults: boolean for boolean YAML defaults, url for keys whose
 * last segment names a URL, string otherwise.
 */
class GeneratedCatalogAssembler {

    private static final String URL_SEGMENT_SUFFIX = "url";

    /**
     * Assembly result.
     *
     * @param catalog regenerated catalog.
     * @param items regeneration diagnostics.
     */
    record Result(ArtemisConfigKeyCatalog catalog, List<ReportItem> items) {
    }

    /**
     * Regenerates the catalog from the generated model's overlay mappings.
     *
     * @param generatedModel assembled generated model.
     * @param yamlScan scanned configuration defaults of the checkout.
     * @param artemisCommit resolved commit of the scanned checkout.
     * @return regenerated catalog and diagnostics.
     */
    Result assemble(FeatureModel generatedModel, ExtractedConfigurationDefaults yamlScan, String artemisCommit) {
        List<ReportItem> items = new ArrayList<>();
        TreeSet<String> keys = new TreeSet<>();
        for (FeatureNode feature : generatedModel.features()) {
            for (ArtifactMapping mapping : feature.artifactMappings()) {
                if (GeneratedModelAssembler.OVERLAY_TARGET.equals(mapping.target())) {
                    keys.add(mapping.path());
                }
            }
        }
        List<ArtemisConfigKeyCatalog.CatalogKey> catalogKeys = new ArrayList<>();
        for (String key : keys) {
            ExtractedConfigurationDefault occurrence = yamlScan.preferredOccurrence(key);
            if (occurrence == null) {
                items.add(ReportItem.info(ReportItem.CODE_CONFIG_KEY_CATALOG_DRIFT, key,
                        "Overlay mapping key '" + key + "' was not observed in the scanned Artemis YAML defaults; its type is derived from the key name."));
            }
            catalogKeys.add(new ArtemisConfigKeyCatalog.CatalogKey(key, keyType(key, occurrence)));
        }
        String source = "Generated by the feature extraction pipeline from the generated model's overlay mappings and the scanned application*.yml defaults.";
        ArtemisConfigKeyCatalog catalog = new ArtemisConfigKeyCatalog(GeneratedModelAssembler.generatedVersion(artemisCommit), artemisCommit, source,
                catalogKeys);
        return new Result(catalog, List.copyOf(items));
    }

    /**
     * Diffs the regenerated catalog against the curated catalog.
     *
     * @param curated curated classpath catalog.
     * @param generated regenerated catalog.
     * @return catalog diff with added and removed keys and type changes.
     */
    ModelDiffReport.CatalogDiff diff(ArtemisConfigKeyCatalog curated, ArtemisConfigKeyCatalog generated) {
        Map<String, String> curatedTypes = typesByKey(curated);
        Map<String, String> generatedTypes = typesByKey(generated);
        List<String> addedKeys = new ArrayList<>();
        List<String> removedKeys = new ArrayList<>();
        List<ModelDiffReport.CatalogDiff.TypeChange> typeChanges = new ArrayList<>();
        for (Map.Entry<String, String> entry : generatedTypes.entrySet()) {
            String curatedType = curatedTypes.get(entry.getKey());
            if (curatedType == null) {
                addedKeys.add(entry.getKey());
            }
            else if (!curatedType.equals(entry.getValue())) {
                typeChanges.add(new ModelDiffReport.CatalogDiff.TypeChange(entry.getKey(), curatedType, entry.getValue()));
            }
        }
        for (String key : curatedTypes.keySet()) {
            if (!generatedTypes.containsKey(key)) {
                removedKeys.add(key);
            }
        }
        addedKeys.sort(String::compareTo);
        removedKeys.sort(String::compareTo);
        typeChanges.sort(Comparator.comparing(ModelDiffReport.CatalogDiff.TypeChange::key));
        return new ModelDiffReport.CatalogDiff(curated.catalogVersion(), curated.verifiedAgainstArtemisCommit(), generated.verifiedAgainstArtemisCommit(),
                List.copyOf(addedKeys), List.copyOf(removedKeys), List.copyOf(typeChanges));
    }

    /**
     * Indexes a catalog's accepted types by key, keeping the catalog order for deterministic iteration.
     *
     * @param catalog catalog to index.
     * @return accepted type per key.
     */
    private Map<String, String> typesByKey(ArtemisConfigKeyCatalog catalog) {
        Map<String, String> typesByKey = new LinkedHashMap<>();
        for (ArtemisConfigKeyCatalog.CatalogKey key : catalog.keys()) {
            typesByKey.putIfAbsent(key.key(), key.type());
        }
        return typesByKey;
    }

    /**
     * Derives the accepted value type of a key from its scanned default and its name.
     *
     * @param key dotted configuration key.
     * @param occurrence preferred scanned default, or null when the key has no YAML default.
     * @return accepted value type.
     */
    private String keyType(String key, ExtractedConfigurationDefault occurrence) {
        if (occurrence != null && occurrence.value() instanceof Boolean) {
            return ArtemisConfigKeyCatalog.TYPE_BOOLEAN;
        }
        String lastSegment = key.substring(key.lastIndexOf('.') + 1);
        if (lastSegment.endsWith(URL_SEGMENT_SUFFIX)) {
            return ArtemisConfigKeyCatalog.TYPE_URL;
        }
        return ArtemisConfigKeyCatalog.TYPE_STRING;
    }
}
